//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNASP.SisAmigos.Windows.Conexao
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_AMIGOSEntities : DbContext
    {
        public DB_AMIGOSEntities()
            : base("name=DB_AMIGOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_AMIGOS> TB_AMIGOS { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
    }
}
