//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNASP.SisAmigos.Windows.Conexao
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class TB_AMIGOS
    {
        [DisplayName("Id")]
        public int ID { get; set; }
        [DisplayName("Nome")]
        public string NOME { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        [DisplayName("Data Nascimento")]
        public System.DateTime DATA_NASCIMENTO { get; set; }
        [DisplayName("Sexo")]
        public string SEXO { get; set; }
        [DisplayName("Estado Civil")]
        public string ESTADO_CIVIL { get; set; }
        [DisplayName("Foto")]
        public byte[] FOTO { get; set; }
    }
}
