//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNASP.SisAmigos.Windows.Conexao
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        public int Id { get; set; }
        public string NOME { get; set; }
        public string USUARIO { get; set; }
        public string SENHA { get; set; }
    }
}
